version: '3.9'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      database:
        condition: service_healthy
    networks:
      - ozon
    command: ["./app", "-db=true", "-config=config/docker.yaml"]
  database:
    container_name: database
    image: postgres
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 1s
      retries: 3
    networks:
      - ozon
networks:
  ozon:
    driver: bridge